name: 自动打包插件

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 打包插件
        run: |
          cd src && zip -r "plugin.mcdr" * -x "skript_command_register/__pycache__/*" -x ".gitignore"

      - name: 检查构建
        run: |
          tree

      - name: 上传插件
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: src/plugin.mcdr